version: '3.7'

services:

  api:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80

  tests:
    ports:
      - 3000:3000
    build:
      context: .
    volumes:
      - .:/usr/src/app
    command: pytest --cov=modules tests/
    # command: pytest  --cov-report=html --cov=modules tests/
