version: '3'

services:

  main:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    command: python ./main.py

  tests:
    ports:
      - 3000:3000
    build:
      context: .
    volumes:
      - .:/usr/src/app
    command: >
      bash -c
      "python tests/linereader.test.py &&
      python tests/pdfparser.test.py &&
      python tests/ccmparser.test.py"
