version: '3.7'

services:

  api:
    build:
      context: .
    volumes:
      - .:/usr/src/app

  tests:
    ports:
      - 3000:3000
    build:
      context: .
    volumes:
      - .:/usr/src/app
    command: >
      bash -c
      "python tests/linereader.test.py &&
      python tests/pdfparser.test.py &&
      python tests/ccmparser.test.py"
